version: "3.8"

services:
  web:
    build: .
    image: real-time-charts-with-flask
    command: python application.py
    environment:
      FLASK_DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:5000:5000"
